name: Psalm Security Scan

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Psalm Security Scan
      uses: docker://ghcr.io/psalm/psalm-security-scan
        
    - name: Upload Security Analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
